
fastlane_version "1.91.0"

default_platform :android

platform :android do
  before_all do
  end

  desc "Deploy app to playstore"
  lane :production do
    supply(json_key_file: ENV["$BITRISEIO_SERVICE_ACCOUNT_JSON_URL"],
    package_name: ENV["$APP_PACKAGE_ID"],
    track: ENV["FASTLANE_TRACK"],
      apk: ["$BITRISE_SIGNED_APK_PATH"],
      skip_upload_metadata: true,
      skip_upload_images: true,
      skip_upload_screenshots: true)
  end
end