
fastlane_version "1.91.0"

default_platform :android

platform :android do
  before_all do
  end

  desc "Deploy app to playstore"
  lane :production do
    supply(json_key: ENV["$BITRISE_SOURCE_DIR"].join('/fastlane/google_play.json').to_s,
    package_name: ENV["$APP_PACKAGE_ID"],
    track: ENV["FASTLANE_TRACK"],
    rollout: '0.5',
    apk: ENV["$BITRISE_SIGNED_APK_PATH"],
    skip_upload_metadata: true,
    skip_upload_images: true,
    skip_upload_screenshots: true)
  end
end